name: "Staged dependencies action"
description: "Github Actions to implement R development stages for package development"
inputs:
  run-system-dependencies:
    description: Check for and install system dependencies
    required: false
    default: false
  git-user-name:
    description: Git user.name configuration for fetching remote staged dependencies
    required: false
    default: github-actions[bot]
  git-user-email:
    description: Git user.email configuration for fetching remote staged dependencies
    required: false
    default: 27856297+dependabot-preview[bot]@users.noreply.github.com
branding:
  icon: 'arrow-down'
  color: 'blue'
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: |
        options(repos = c(CRAN = "https://cloud.r-project.org/"))
        ncores <- parallel::detectCores(all.tests = FALSE, logical = TRUE)
        if (!require("remotes")) install.packages("remotes", upgrade = "never", Ncpus = ncores)
      shell: Rscript {0}

    - name: Run system dependencies
      run: |
        if [ "${{ inputs.run-system-dependencies }}" = "true" ]
        then {
          SUDO_CMD=""
          if [ "$(whoami)" != "root" ]
          then {
            SUDO_CMD="sudo "
          }
          fi
          ${SUDO_CMD}${GITHUB_ACTION_PATH}/system-dependencies.R
        }
        fi
      shell: bash

    - name: Set git user.name and user.email configurations
      run: |
        git config --global user.name "${{ inputs.git-user-name }}"
        git config --global user.email "${{ inputs.git-user-email }}"
        git config --global --add safe.directory $(pwd)
      shell: bash

    - name: Run staged dependencies
      run: ${GITHUB_ACTION_PATH}/staged-dependencies.R
      shell: bash
      env:
        SD_GIT_REF: ${{ github.ref }}

    - name: Unset git user.name and user.email configurations
      run: |
        git config --global --unset user.name
        git config --global --unset user.email
      shell: bash
