name: "Staged dependencies action"
description: "Github Actions to implement R development stages for package development"
inputs:
  staged-dependencies-version:
    description: "Version of staged.dependencies"
    required: true
    default: "v0.2.2"
  path:
    description: "Path to R package"
    required: true
    default: "."
## Add consistency check
runs:
  using: "composite"
  steps:
      - name: Install dependencies
        run: |
          if (!require("remotes")) install.packages("remotes", repos="http://cran.us.r-project.org", upgrade = "never")
        shell: Rscript {0}

      - name: Run system dependencies
        run: ${GITHUB_ACTION_PATH}/install-staged-dependencies.R "${{ inputs.path }}" "${{ inputs.staged-dependencies-version }}"
        shell: sh

