name: "Staged dependencies action"
description: "Github Actions to implement R development stages for package development"
inputs:
  run-system-dependencies:
    description: Check for and install system dependencies
    required: false
    default: false
  use-cache:
    description: Use GitHub's caching mechanism to cache staged dependencies
    required: false
    default: true
branding:
  icon: 'arrow-down'
  color: 'blue'
runs:
  using: "composite"
  steps:
    - name: Run system dependencies
      run: |
        if [ "${{ inputs.run-system-dependencies }}" = "true" ]
        then {
          ${GITHUB_ACTION_PATH}/system-dependencies.R
        }
        fi
      shell: bash

    - name: Check if staged.deps config exists
      if: ${{ inputs.use-cache == 'true' }}
      id: check_staged_deps
      uses: andstor/file-existence-action@v1
      with:
        files: staged_dependencies.yaml

    - name: Restore cache
      if: ${{ inputs.use-cache == 'true' && steps.check_staged_deps.outputs.files_exists == 'true' }}
      uses: actions/cache@v3
      with:
        path: |
          ~/.staged.dependencies
        key: staged-deps-${{ hashFiles('staged_dependencies.yaml') }}

    - name: Run staged dependencies
      run: ${GITHUB_ACTION_PATH}/staged-dependencies.R
      shell: bash
      env:
        SD_GIT_REF: ${{ github.ref }}
