name: "Staged dependencies action"
description: "Github Actions to implement R development stages for package development"
inputs:
  run-system-dependencies:
    description: Check for and install system dependencies
    required: false
    default: false
  git-user-name:
    description: Git user.name configuration for fetching remote staged dependencies
    required: false
    default: github-actions[bot]
  git-user-email:
    description: Git user.email configuration for fetching remote staged dependencies
    required: false
    default: 27856297+dependabot-preview[bot]@users.noreply.github.com
branding:
  icon: 'arrow-down'
  color: 'blue'
runs:
  using: "composite"
  steps:
    - name: Run system dependencies
      run: |
        if [ "${{ inputs.run-system-dependencies }}" = "true" ]
        then {
          ${GITHUB_ACTION_PATH}/system-dependencies.R
        }
        fi
      shell: bash

    - name: Run staged dependencies
      run: ${GITHUB_ACTION_PATH}/staged-dependencies.R
      shell: bash
      env:
        SD_GIT_REF: ${{ github.ref }}
